/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college_data_management_system.by_ashutosh_gupta;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author user
 */
public class Course_Fee_Structure_page extends javax.swing.JFrame {

    private final String loggedInUserId;

    /**
     * Creates new form Course_Fee_Structure
     */
    public Course_Fee_Structure_page(String userId) {
        this.loggedInUserId = userId;
        initComponents();
        loadFeeData(); // call load logic on page open
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        L9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TF = new javax.swing.JTextField();
        L8 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        L6 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        L10 = new javax.swing.JLabel();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        CB1 = new javax.swing.JCheckBox();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(",");

        jLabel8.setText("ashut99");

        jLabel9.setText("Ashu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Padma College of Expertise");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Dear, Aspirant");

        jLabel3.setText("Please select your Course");

        CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.A", "B.Sc", "B.Com", "BCA", "BBA", "BMS", "BEM", "BJMC", "BFD", "BSW", "BBS", "BTTM", "B.Voc", "BALLB", " " }));
        CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBActionPerformed(evt);
            }
        });

        jLabel4.setText("Registration Fee");

        jLabel5.setText("Form Fee");

        jLabel6.setText("Exam Fee");

        jLabel10.setText("Admission Fee");

        jLabel11.setText("Library Fee");

        jLabel12.setText("Semester 1, 2 Combined Fee");

        jLabel13.setText("Semester 1, 2 Combined Exam Fee");

        jLabel14.setText("Doonation for poor childrens");

        jLabel15.setText("Practical Fee");

        jLabel16.setText("Course Chosen");

        L9.setText("0");

        jLabel18.setText("Total Ammount");

        TF.setText("0");
        TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFActionPerformed(evt);
            }
        });

        L8.setText("0");

        L7.setText("0");

        L6.setText("0");

        L5.setText("0");

        L4.setText("0");

        L3.setText("0");

        L2.setText("0");

        L1.setText(".");

        L10.setText("0");

        B1.setText("Submit");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.setText("Reset");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setText("Exit");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        CB1.setText("Once submitted cannot be changed");
        CB1.setEnabled(false);
        CB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB1ActionPerformed(evt);
            }
        });

        B4.setText("Check & Submit");
        B4.setEnabled(false);
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setText("Cancel and Edit");
        B5.setEnabled(false);
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("We are, Padma Colledge of Expertise our one and only goal");

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("to make everyone super special in their interest subjects.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(B5)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(CB1)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(B1)
                                            .addGap(69, 69, 69)
                                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(58, 58, 58)
                                    .addComponent(B3))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(L2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(L3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(L4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(L5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(L6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(L7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(L8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(L9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(L10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))
                                        .addGap(170, 170, 170))
                                    .addComponent(L1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(B4)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3)
                    .addComponent(CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(L1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(L2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(L3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(L4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(L5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(L6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L8)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L9)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(L10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B1)
                    .addComponent(B2)
                    .addComponent(B3))
                .addGap(18, 18, 18)
                .addComponent(CB1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(B4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateUserDetails() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/colledge_database", "root", "");

            // Update only for this user
            String query = "UPDATE login_data SET course=?, Fee=?, fee_lock=1 WHERE User_ID=?";
            PreparedStatement pst = conn.prepareStatement(query);

            // Get selected course (combo box value, for DB field 'course')
            String course = (CB.getSelectedItem() != null) ? CB.getSelectedItem().toString() : "";

            // Get the final total fee from L10 label (not the editable field TF)
            int totalFee = 0;
            try {
                totalFee = Integer.parseInt(L10.getText());
            } catch (Exception ex) {
                // fallback: try TF field, if needed
                try {
                    totalFee = Integer.parseInt(TF.getText());
                } catch (Exception ignore) {
                }
            }

            pst.setString(1, course); // course name
            pst.setInt(2, totalFee); // final total fee
            pst.setString(3, loggedInUserId); // update only current user

            int rs = pst.executeUpdate();
            if (rs > 0) {
                JOptionPane.showMessageDialog(this, "Course & Fee submitted and locked!"); // success
            } else {
                JOptionPane.showMessageDialog(this, "Update failed! User not found?");
            }

            pst.close();
            conn.close();

            // Lock the page after update for this user
            CB.setEnabled(false);
            TF.setEnabled(false);
            B1.setEnabled(false);
            B2.setEnabled(false);
            B3.setEnabled(false);
            CB1.setEnabled(false);
            CB1.setSelected(true);
            B4.setEnabled(false);
            B5.setEnabled(false);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        int b, c, d, e, f, g, h, i, j, k, l;
        b = Integer.parseInt(L2.getText());
        c = Integer.parseInt(L3.getText());
        d = Integer.parseInt(L4.getText());
        e = Integer.parseInt(L5.getText());
        f = Integer.parseInt(L6.getText());
        g = Integer.parseInt(L7.getText());
        h = Integer.parseInt(L8.getText());
        i = Integer.parseInt(L9.getText());
        j = Integer.parseInt(TF.getText());
        k = b + c + d + e + f + g + h + i + j;
        L10.setText("" + k);

        CB.setEnabled(false);
        TF.setEnabled(false);
        B1.setEnabled(false);
        B2.setEnabled(false);
        B3.setEnabled(false);
        CB1.setEnabled(true);
        B5.setEnabled(true);
    }// GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_B2ActionPerformed

        L1.setText(".");
        L2.setText("0");
        L3.setText("0");
        L4.setText("0");
        L5.setText("0");
        L6.setText("0");
        L7.setText("0");
        L8.setText("0");
        L9.setText("0");
        TF.setText("0");
        L10.setText("0");
    }// GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_B3ActionPerformed
        System.exit(0);
    }// GEN-LAST:event_B3ActionPerformed

    private void CB1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CB1ActionPerformed
        // TODO add your handling code here:
        CB1.setEnabled(false);
        B4.setEnabled(true);
        B5.setEnabled(false);
    }// GEN-LAST:event_CB1ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_B4ActionPerformed
        updateUserDetails();
        this.setVisible(false);
        new Paymet_page(loggedInUserId).setVisible(true);
    }// GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
        CB.setEnabled(true);
        TF.setEnabled(true);
        B1.setEnabled(true);
        B2.setEnabled(true);
        B3.setEnabled(true);
        CB1.setEnabled(false);
        B5.setEnabled(false);
    }// GEN-LAST:event_B5ActionPerformed

    private void CBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CBActionPerformed
        // TODO add your handling code here:
        String a = CB.getSelectedItem().toString();
        if (a == "B.A") {
            L1.setText("B.A - Bachelor of Arts");
            L2.setText("100");
            L3.setText("150");
            L4.setText("750");
            L5.setText("7200");
            L6.setText("1500");
            L7.setText("10000");
            L8.setText("0");
            L9.setText("2000");
        } else if (a == "B.Sc") {
            L1.setText("B.Sc - Bachelor of Science");
            L2.setText("100");
            L3.setText("150");
            L4.setText("750");
            L5.setText("7200");
            L6.setText("1500");
            L7.setText("14500");
            L8.setText("1500");
            L9.setText("2000");
        } else if (a == "B.Com") {
            L1.setText("B.Com - Bachelor of Commerce");
            L2.setText("100");
            L3.setText("150");
            L4.setText("750");
            L5.setText("7200");
            L6.setText("1500");
            L7.setText("19000");
            L8.setText("0");
            L9.setText("2000");
        } else if (a == "BCA") {
            L1.setText("BCA - Bachelor of Computer Applications");
            L2.setText("100");
            L3.setText("150");
            L4.setText("750");
            L5.setText("7200");
            L6.setText("1500");
            L7.setText("32000");
            L8.setText("4500");
            L9.setText("3500");
        } else if (a == "BBA") {
            L1.setText("BBA - Bachelor of Business Administration");
            L2.setText("100");
            L3.setText("150");
            L4.setText("750");
            L5.setText("7200");
            L6.setText("1500");
            L7.setText("60000");
            L8.setText("4500");
            L9.setText("4200");
        } else if (a == "BMS") {
            L1.setText("BMS - Bachelor of Management Science");
            L2.setText("100");
            L3.setText("150");
            L4.setText("750");
            L5.setText("7200");
            L6.setText("1500");
            L7.setText("14500");
            L8.setText("500");
            L9.setText("2000");
        } else if (a == "BEM") {
            L1.setText("BEM - Bachelor of Event Management");
            L2.setText("100");
            L3.setText("150");
            L4.setText("750");
            L5.setText("7200");
            L6.setText("1500");
            L7.setText("22000");
            L8.setText("4500");
            L9.setText("3200");
        } else if (a == "BJMC") {
            L1.setText("BJMC - Bachelor of Journalism and Mass Communication");
            L2.setText("100");
            L3.setText("150");
            L4.setText("750");
            L5.setText("7200");
            L6.setText("1500");
            L7.setText("22000");
            L8.setText("4500");
            L9.setText("3200");
        } else if (a == "BFD") {
            L1.setText("BFD - Bachelor of Fashion Designing");
            L2.setText("100");
            L3.setText("150");
            L4.setText("750");
            L5.setText("7200");
            L6.setText("1500");
            L7.setText("22000");
            L8.setText("4500");
            L9.setText("3200");
        } else if (a == "BSW") {
            L1.setText("BSW - Bachelor of Social Work");
            L2.setText("100");
            L3.setText("150");
            L4.setText("750");
            L5.setText("7200");
            L6.setText("1500");
            L7.setText("12000");
            L8.setText("0");
            L9.setText("350");
        } else if (a == "BBS") {
            L1.setText("BBS - Bachelor of Business Studies");
            L2.setText("100");
            L3.setText("150");
            L4.setText("750");
            L5.setText("7200");
            L6.setText("1500");
            L7.setText("60000");
            L8.setText("4500");
            L9.setText("4100");
        } else if (a == "BTTM") {
            L1.setText("BTTM - Bachelor of Travel and Tourism Management");
            L2.setText("100");
            L3.setText("150");
            L4.setText("750");
            L5.setText("7200");
            L6.setText("1500");
            L7.setText("55000");
            L8.setText("4450");
            L9.setText("4150");
        } else if (a == "B.Voc") {
            L1.setText("B.Voc - Bachelor of Vocation");
            L2.setText("100");
            L3.setText("150");
            L4.setText("750");
            L5.setText("7200");
            L6.setText("1500");
            L7.setText("40000");
            L8.setText("0");
            L9.setText("3200");
        } else if (a == "BALLB") {
            L1.setText("BALLB - Integarted Bachelor of Arts and Bachelor of Legislative Law");
            L2.setText("100");
            L3.setText("150");
            L4.setText("750");
            L5.setText("7200");
            L6.setText("1500");
            L7.setText("75000");
            L8.setText("0");
            L9.setText("6000");
        } else {
            L1.setText(".");
            L2.setText("0");
            L3.setText("0");
            L4.setText("0");
            L5.setText("0");
            L6.setText("0");
            L7.setText("0");
            L8.setText("0");
            L9.setText("0");
            TF.setText("0");
            L10.setText("0");
            JOptionPane.showMessageDialog(null, "Wrong Selection");
        }
    }// GEN-LAST:event_CBActionPerformed

    private void TFActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TFActionPerformed

    }// GEN-LAST:event_TFActionPerformed

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    // /* Set the Nimbus look and feel */
    // // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // // (optional) ">
    // /*
    // * If Nimbus (introduced in Java SE 6) is not available, stay with the default
    // * look and feel.
    // * For details see
    // * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
    // */
    // try {
    // for (javax.swing.UIManager.LookAndFeelInfo info :
    // javax.swing.UIManager.getInstalledLookAndFeels()) {
    // if ("Nimbus".equals(info.getName())) {
    // javax.swing.UIManager.setLookAndFeel(info.getClassName());
    // break;
    // }
    // }
    // } catch (ClassNotFoundException ex) {
    // java.util.logging.Logger.getLogger(Course_Fee_Structure_page.class.getName())
    // .log(java.util.logging.Level.SEVERE, null, ex);
    // } catch (InstantiationException ex) {
    // java.util.logging.Logger.getLogger(Course_Fee_Structure_page.class.getName())
    // .log(java.util.logging.Level.SEVERE, null, ex);
    // } catch (IllegalAccessException ex) {
    // java.util.logging.Logger.getLogger(Course_Fee_Structure_page.class.getName())
    // .log(java.util.logging.Level.SEVERE, null, ex);
    // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    // java.util.logging.Logger.getLogger(Course_Fee_Structure_page.class.getName())
    // .log(java.util.logging.Level.SEVERE, null, ex);
    // }
    // // </editor-fold>
    // // </editor-fold>
    //
    // /* Create and display the form */
    // java.awt.EventQueue.invokeLater(new Runnable() {
    // public void run() {
    // new Course_Fee_Structure_page().setVisible(true);
    // }
    // });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JComboBox<String> CB;
    private javax.swing.JCheckBox CB1;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JLabel L8;
    private javax.swing.JLabel L9;
    private javax.swing.JTextField TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void loadFeeData() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/colledge_database", "root", "");
            String query = "SELECT * FROM login_data WHERE User_ID = ?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, loggedInUserId);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                // Set user info at the top
                jLabel8.setText(rs.getString("User_ID"));
                jLabel9.setText(rs.getString("Name"));

                String course = rs.getString("course");
                int fee = rs.getInt("Fee");
                int feeLock = rs.getInt("fee_lock");

                if (course != null && !course.trim().isEmpty()) {
                    CB.setSelectedItem(course);
                }

                // Always set the full fee structure as per selected course (from your dropdown
                // logic)
                setFeeStructureByCourse(course);

                // Set the final total amount as in DB
                L10.setText(String.valueOf(fee));

                // Calculate and display donation (TF): Fee - sum of other components
                int b = Integer.parseInt(L2.getText());
                int c = Integer.parseInt(L3.getText());
                int d = Integer.parseInt(L4.getText());
                int e = Integer.parseInt(L5.getText());
                int f_ = Integer.parseInt(L6.getText());
                int g = Integer.parseInt(L7.getText());
                int h = Integer.parseInt(L8.getText());
                int i = Integer.parseInt(L9.getText());
                int sum = fee; // as from DB
                int k = sum - (b + c + d + e + f_ + g + h + i);
                TF.setText(String.valueOf(k));

                if (feeLock == 1) {
                    // Lock everything (except B4, which must be enabled for payment)
                    CB.setEnabled(false);
                    TF.setEnabled(false);
                    B1.setEnabled(false);
                    B2.setEnabled(false);
                    B3.setEnabled(false);
                    CB1.setEnabled(false);
                    CB1.setSelected(true); // show confirmed
                    B4.setEnabled(true); // Payment button
                    B5.setEnabled(false);
                }
            }
            rs.close();
            pst.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading fee data: " + e.getMessage());
        }
    }

    /**
     * Helper function: fill all L1-L9 labels according to course name,
     * exactly as in your CBActionPerformed.
     * Call this from loadFeeData() so fee structure always matches course field in
     * DB.
     */
    private void setFeeStructureByCourse(String course) {
        if (course == null)
            course = "";
        switch (course.trim()) {
            case "B.A":
                L1.setText("B.A - Bachelor of Arts");
                L2.setText("100");
                L3.setText("150");
                L4.setText("750");
                L5.setText("7200");
                L6.setText("1500");
                L7.setText("10000");
                L8.setText("0");
                L9.setText("2000");
                break;
            case "B.Sc":
                L1.setText("B.Sc - Bachelor of Science");
                L2.setText("100");
                L3.setText("150");
                L4.setText("750");
                L5.setText("7200");
                L6.setText("1500");
                L7.setText("14500");
                L8.setText("1500");
                L9.setText("2000");
                break;
            case "B.Com":
                L1.setText("B.Com - Bachelor of Commerce");
                L2.setText("100");
                L3.setText("150");
                L4.setText("750");
                L5.setText("7200");
                L6.setText("1500");
                L7.setText("19000");
                L8.setText("0");
                L9.setText("2000");
                break;
            case "BCA":
                L1.setText("BCA - Bachelor of Computer Applications");
                L2.setText("100");
                L3.setText("150");
                L4.setText("750");
                L5.setText("7200");
                L6.setText("1500");
                L7.setText("32000");
                L8.setText("4500");
                L9.setText("3500");
                break;
            case "BBA":
                L1.setText("BBA - Bachelor of Business Administration");
                L2.setText("100");
                L3.setText("150");
                L4.setText("750");
                L5.setText("7200");
                L6.setText("1500");
                L7.setText("60000");
                L8.setText("4500");
                L9.setText("4200");
                break;
            case "BMS":
                L1.setText("BMS - Bachelor of Management Science");
                L2.setText("100");
                L3.setText("150");
                L4.setText("750");
                L5.setText("7200");
                L6.setText("1500");
                L7.setText("14500");
                L8.setText("500");
                L9.setText("2000");
                break;
            case "BEM":
                L1.setText("BEM - Bachelor of Event Management");
                L2.setText("100");
                L3.setText("150");
                L4.setText("750");
                L5.setText("7200");
                L6.setText("1500");
                L7.setText("22000");
                L8.setText("4500");
                L9.setText("3200");
                break;
            case "BJMC":
                L1.setText("BJMC - Bachelor of Journalism and Mass Communication");
                L2.setText("100");
                L3.setText("150");
                L4.setText("750");
                L5.setText("7200");
                L6.setText("1500");
                L7.setText("22000");
                L8.setText("4500");
                L9.setText("3200");
                break;
            case "BFD":
                L1.setText("BFD - Bachelor of Fashion Designing");
                L2.setText("100");
                L3.setText("150");
                L4.setText("750");
                L5.setText("7200");
                L6.setText("1500");
                L7.setText("22000");
                L8.setText("4500");
                L9.setText("3200");
                break;
            case "BSW":
                L1.setText("BSW - Bachelor of Social Work");
                L2.setText("100");
                L3.setText("150");
                L4.setText("750");
                L5.setText("7200");
                L6.setText("1500");
                L7.setText("12000");
                L8.setText("0");
                L9.setText("350");
                break;
            case "BBS":
                L1.setText("BBS - Bachelor of Business Studies");
                L2.setText("100");
                L3.setText("150");
                L4.setText("750");
                L5.setText("7200");
                L6.setText("1500");
                L7.setText("60000");
                L8.setText("4500");
                L9.setText("4100");
                break;
            case "BTTM":
                L1.setText("BTTM - Bachelor of Travel and Tourism Management");
                L2.setText("100");
                L3.setText("150");
                L4.setText("750");
                L5.setText("7200");
                L6.setText("1500");
                L7.setText("55000");
                L8.setText("4450");
                L9.setText("4150");
                break;
            case "B.Voc":
                L1.setText("B.Voc - Bachelor of Vocation");
                L2.setText("100");
                L3.setText("150");
                L4.setText("750");
                L5.setText("7200");
                L6.setText("1500");
                L7.setText("40000");
                L8.setText("0");
                L9.setText("3200");
                break;
            case "BALLB":
                L1.setText("BALLB - Integarted Bachelor of Arts and Bachelor of Legislative Law");
                L2.setText("100");
                L3.setText("150");
                L4.setText("750");
                L5.setText("7200");
                L6.setText("1500");
                L7.setText("75000");
                L8.setText("0");
                L9.setText("6000");
                break;
            default:
                L1.setText(".");
                L2.setText("0");
                L3.setText("0");
                L4.setText("0");
                L5.setText("0");
                L6.setText("0");
                L7.setText("0");
                L8.setText("0");
                L9.setText("0");
                break;
        }
    }
}
